### PR TITLE
daiyr add utlites

### PR DESCRIPTION
**Pull request by daiyrisa**
i did changed pom.xml

### CODE REVIEW

**Review by MarselErlan — APPROVED** [review]
again good

**Review by helenSpring123 — APPROVED** [review]
good job

**Review by milu3300 — APPROVED** [review]

**Review by Abduvokhidjon — APPROVED** [review]

**Review by milu3300 — APPROVED** [review]
good

**Review by milu3300 — APPROVED** [review]
goood

**Comment by MarselErlan** [comment]
good

**Pull request merged**
